package com.ssafy.a405.domain.video.entity;

import com.ssafy.a405.global.common.base.BaseTimeEntity;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Entity
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Table(name = "`영상 자막`")
public class VideoSubtitle extends BaseTimeEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "video_id", nullable = false)
    private Video video;

    @Column(name = "raw_text", columnDefinition = "LONGTEXT")
    private String rawText;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated;

    @Builder
    public VideoSubtitle(Video video, String rawText, Boolean isAutoGenerated) {
        this.video = video;
        this.rawText = rawText;
        this.isAutoGenerated = isAutoGenerated;
    }
}
