package com.ssafy.a405.domain.analysis.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ssafy.a405.domain.analysis.entity.AnalysisResult;
import com.ssafy.a405.domain.analysis.entity.ViolationDetail;
import com.ssafy.a405.domain.analysis.repository.AnalysisResultRepository;
import com.ssafy.a405.domain.analysis.repository.ViolationDetailRepository;
import com.ssafy.a405.domain.channel.entity.Channel;
import com.ssafy.a405.domain.channel.repository.ChannelRepository;
import com.ssafy.a405.domain.video.entity.Video;
import com.ssafy.a405.domain.video.entity.VideoScript;
import com.ssafy.a405.domain.video.repository.VideoRepository;
import com.ssafy.a405.domain.video.repository.VideoScriptRepository;
import com.ssafy.a405.global.common.enums.TrustGrade;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@RequiredArgsConstructor
public class AnalysisDataMappingService {

    private final ObjectMapper objectMapper;
    private final ChannelRepository channelRepository;
    private final VideoRepository videoRepository;
    private final VideoScriptRepository videoScriptRepository;
    private final AnalysisResultRepository analysisResultRepository;
    private final ViolationDetailRepository violationDetailRepository;

    private static final String UNKNOWN_CHANNEL_PREFIX = "__UNKNOWN_CHANNEL__:";
    private static final String DEFAULT_CHANNEL_NAME = "Unknown Channel";

    @Transactional
    public void mapAndSaveAnalysisResult(String resultJson) {
        if (resultJson == null || resultJson.isBlank()) {
            return;
        }

        try {
            JsonNode root = objectMapper.readTree(resultJson);
            JsonNode transcriptNode = root.path("transcript");
            JsonNode analysisNode = root.path("analysis").path("analysisResult");

            boolean legacyShape = !(transcriptNode.isMissingNode() || analysisNode.isMissingNode());
            if (!legacyShape) {
                mapAndSaveFromFinalPayload(root);
                return;
            }

            // 2. Video
            String videoIdStr = transcriptNode.path("video_id").asText(null);
            if (videoIdStr == null || videoIdStr.isBlank()) {
                log.warn("Missing video_id in transcript payload. Skipping RDB mapping for channel/video.");
                return;
            }
            String videoTitle = transcriptNode.path("title").asText("");

            // 1. Channel
            String channelIdStr = transcriptNode.path("channel_id").asText(null);
            if (channelIdStr == null || channelIdStr.isBlank()) {
                // [AI 리뷰 반영] 실제 채널 ID와 절대 충돌하지 않을 패턴으로 수정
                channelIdStr = UNKNOWN_CHANNEL_PREFIX + videoIdStr;
            }
            String channelName = transcriptNode.path("author").asText(DEFAULT_CHANNEL_NAME);

            final String finalChannelId = channelIdStr;
            Channel channel = channelRepository.findByYtChannelId(finalChannelId)
                    .orElseGet(() -> channelRepository.save(Channel.builder()
                            .ytChannelId(finalChannelId)
                            .channelName(channelName)
                            .trustGrade(TrustGrade.UNKNOWN)
                            .totalViolationCount(0)
                            .build()));

            Video video = videoRepository.findByYtVideoId(videoIdStr)
                    .orElseGet(() -> videoRepository.save(Video.builder()
                            .ytVideoId(videoIdStr)
                            .title(videoTitle)
                            .channel(channel)
                            .build()));

            // 3. VideoScript
            String content = transcriptNode.path("content").asText("");
            boolean isWhisper = transcriptNode.path("is_whisper").asBoolean(false);

            VideoScript videoScript = videoScriptRepository.findByVideoId(video.getId())
                    .orElseGet(() -> VideoScript.builder()
                            .video(video)
                            .rawText(content)
                            .isAutoGenerated(isWhisper)
                            .build());
            videoScript.updateRawText(content, isWhisper);
            videoScriptRepository.save(videoScript);

            // 4. AnalysisResult
            String trustGradeStr = analysisNode.path("trustGrade").asText("UNKNOWN");
            TrustGrade tempTrustGrade;
            try {
                tempTrustGrade = TrustGrade.valueOf(trustGradeStr.toUpperCase());
            } catch (IllegalArgumentException e) {
                tempTrustGrade = TrustGrade.UNKNOWN;
            }
            final TrustGrade trustGrade = tempTrustGrade;

            Integer confidenceScore = analysisNode.path("confidenceScore").isMissingNode() ? null : analysisNode.path("confidenceScore").asInt();
            String summary = analysisNode.path("summary").asText("");
            String modelVersion = analysisNode.path("modelVersion").asText("unknown");

            AnalysisResult analysisResult = analysisResultRepository.findByVideoId(video.getId())
                    .orElseGet(() -> AnalysisResult.builder()
                            .video(video)
                            .status(trustGrade)
                            .confidenceScore(confidenceScore)
                            .summary(summary)
                            .modelVersion(modelVersion)
                            .build());
            analysisResult.updateResult(confidenceScore, trustGrade, summary, modelVersion);
            analysisResult = analysisResultRepository.save(analysisResult);

            // 5. ViolationDetails
            if (analysisResult.getId() != null) {
                violationDetailRepository.deleteByAnalysisResultId(analysisResult.getId());
            }
            JsonNode violationsNode = root.path("analysis").path("violations");
            if (violationsNode.isArray()) {
                for (JsonNode vNode : violationsNode) {
                    Integer startTime = vNode.path("startTime").isMissingNode() ? null : vNode.path("startTime").asInt();
                    String violationSentence = vNode.path("violationSentence").asText("");
                    String reason = vNode.path("reason").asText("");

                    violationDetailRepository.save(ViolationDetail.builder()
                            .analysisResult(analysisResult)
                            .startTime(startTime)
                            .violationSentence(violationSentence)
                            .reason(reason)
                            .build());
                }
            }

            log.info("Successfully mapped and saved AnalysisResult for videoId={}", videoIdStr);

        } catch (Exception e) {
            log.error("analysis.mapping_failed payloadChars={}", resultJson == null ? 0 : resultJson.length(), e);
        }
    }

    private void mapAndSaveFromFinalPayload(JsonNode root) {
        String videoIdStr = root.path("videoId").asText(null);
        if (videoIdStr == null || videoIdStr.isBlank()) {
            log.warn("Missing videoId in final payload resultJson. Skipping mapping.");
            return;
        }

        String channelIdStr = root.path("channelId").asText(null);
        if (channelIdStr == null || channelIdStr.isBlank()) {
            channelIdStr = UNKNOWN_CHANNEL_PREFIX + videoIdStr;
        }

        String channelName = root.path("channelName").asText(DEFAULT_CHANNEL_NAME);
        final String finalChannelId = channelIdStr;
        Channel channel = channelRepository.findByYtChannelId(finalChannelId)
            .orElseGet(() -> channelRepository.save(Channel.builder()
                .ytChannelId(finalChannelId)
                .channelName(channelName)
                .trustGrade(TrustGrade.UNKNOWN)
                .totalViolationCount(0)
                .build()));

        String videoTitle = root.path("videoTitle").asText("");
        Video video = videoRepository.findByYtVideoId(videoIdStr)
            .orElseGet(() -> videoRepository.save(Video.builder()
                .ytVideoId(videoIdStr)
                .title(videoTitle)
                .channel(channel)
                .build()));

        String trustGradeStr = root.path("trustGrade").asText("UNKNOWN");
        TrustGrade tempTrustGrade;
        try {
            tempTrustGrade = TrustGrade.valueOf(trustGradeStr.toUpperCase());
        } catch (IllegalArgumentException e) {
            tempTrustGrade = TrustGrade.UNKNOWN;
        }
        final TrustGrade trustGrade = tempTrustGrade;

        Integer confidenceScore = root.path("confidenceScore").isMissingNode() ? null : root.path("confidenceScore").asInt();
        String summary = root.path("summary").asText("");
        String modelVersion = root.path("modelVersion").asText("unknown");

        AnalysisResult analysisResult = analysisResultRepository.findByVideoId(video.getId())
            .orElseGet(() -> AnalysisResult.builder()
                .video(video)
                .status(trustGrade)
                .confidenceScore(confidenceScore == null ? 0 : confidenceScore)
                .summary(summary)
                .modelVersion(modelVersion)
                .build());
        analysisResult.updateResult(confidenceScore == null ? 0 : confidenceScore, trustGrade, summary, modelVersion);
        analysisResult = analysisResultRepository.save(analysisResult);

        JsonNode violationsNode = root.path("violations");
        if (violationsNode.isArray()) {
            if (analysisResult.getId() != null) {
                violationDetailRepository.deleteByAnalysisResultId(analysisResult.getId());
            }
            for (JsonNode vNode : violationsNode) {
                Integer startTime = vNode.path("startTime").isMissingNode() ? null : vNode.path("startTime").asInt();
                String violationSentence = vNode.path("violationSentence").asText("");
                String reason = vNode.path("reason").asText("");

                violationDetailRepository.save(ViolationDetail.builder()
                    .analysisResult(analysisResult)
                    .startTime(startTime)
                    .violationSentence(violationSentence)
                    .reason(reason)
                    .build());
            }
        }

        log.info("Successfully mapped and saved AnalysisResult(final payload) for videoId={}", videoIdStr);
    }
}
