package com.ssafy.a405.domain.analysis.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ssafy.a405.domain.analysis.entity.AnalysisResult;
import com.ssafy.a405.domain.analysis.entity.ViolationDetail;
import com.ssafy.a405.domain.analysis.repository.AnalysisResultRepository;
import com.ssafy.a405.domain.analysis.repository.ViolationDetailRepository;
import com.ssafy.a405.domain.channel.entity.Channel;
import com.ssafy.a405.domain.channel.repository.ChannelRepository;
import com.ssafy.a405.domain.video.entity.Video;
import com.ssafy.a405.domain.video.entity.VideoScript;
import com.ssafy.a405.domain.video.repository.VideoRepository;
import com.ssafy.a405.domain.video.repository.VideoScriptRepository;
import com.ssafy.a405.global.common.enums.TrustGrade;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@RequiredArgsConstructor
public class AnalysisDataMappingService {

    private final ObjectMapper objectMapper;
    private final ChannelRepository channelRepository;
    private final VideoRepository videoRepository;
    private final VideoScriptRepository videoScriptRepository;
    private final AnalysisResultRepository analysisResultRepository;
    private final ViolationDetailRepository violationDetailRepository;

    @Transactional
    public void mapAndSaveAnalysisResult(String resultJson) {
        if (resultJson == null || resultJson.isBlank()) {
            return;
        }

        try {
            JsonNode root = objectMapper.readTree(resultJson);
            JsonNode transcriptNode = root.path("transcript");
            JsonNode analysisNode = root.path("analysis").path("analysisResult");

            boolean legacyShape = !(transcriptNode.isMissingNode() || analysisNode.isMissingNode());
            if (!legacyShape) {
                // Kafka mode typically stores the analysis.completed payload directly (final result shape),
                // which does not include "transcript"/"analysis" wrapper nodes.
                mapAndSaveFromFinalPayload(root);
                return;
            }

            // 1. Channel
            String channelIdStr = transcriptNode.path("channel_id").asText();
            String channelName = transcriptNode.path("author").asText();

            Channel channel = channelRepository.findByYtChannelId(channelIdStr)
                    .orElseGet(() -> channelRepository.save(Channel.builder()
                            .ytChannelId(channelIdStr)
                            .channelName(channelName)
                            .trustGrade(TrustGrade.UNKNOWN) // Will be updated later if needed
                            .totalViolationCount(0)
                            .build()));

            // 2. Video
            String videoIdStr = transcriptNode.path("video_id").asText();
            String videoTitle = transcriptNode.path("title").asText();

            Video video = videoRepository.findByYtVideoId(videoIdStr)
                    .orElseGet(() -> videoRepository.save(Video.builder()
                            .ytVideoId(videoIdStr)
                            .title(videoTitle)
                            .channel(channel)
                            // thumbnailUrl, description, publishedAt can be updated later if Youtube API is used directly
                            .build()));

            // 3. VideoScript
            String content = transcriptNode.path("content").asText();
            boolean isWhisper = transcriptNode.path("is_whisper").asBoolean(false);

            VideoScript videoScript = videoScriptRepository.findByVideoId(video.getId())
                    .orElseGet(() -> VideoScript.builder()
                            .video(video)
                            .rawText(content)
                            .isAutoGenerated(isWhisper)
                            .build());
            videoScript.updateRawText(content, isWhisper);
            videoScriptRepository.save(videoScript);

            // 4. AnalysisResult
            String trustGradeStr = analysisNode.path("trustGrade").asText("UNKNOWN");
            TrustGrade tempTrustGrade;
            try {
                tempTrustGrade = TrustGrade.valueOf(trustGradeStr.toUpperCase());
            } catch (IllegalArgumentException e) {
                tempTrustGrade = TrustGrade.UNKNOWN;
            }
            final TrustGrade trustGrade = tempTrustGrade;

            Integer confidenceScore = analysisNode.path("confidenceScore").isMissingNode() ? null : analysisNode.path("confidenceScore").asInt();
            String summary = analysisNode.path("summary").asText("");
            String modelVersion = analysisNode.path("modelVersion").asText("unknown");

            AnalysisResult analysisResult = analysisResultRepository.findByVideoId(video.getId())
                    .orElseGet(() -> AnalysisResult.builder()
                            .video(video)
                            .status(trustGrade)
                            .confidenceScore(confidenceScore)
                            .summary(summary)
                            .modelVersion(modelVersion)
                            .build());
            analysisResult.updateResult(confidenceScore, trustGrade, summary, modelVersion);
            analysisResult = analysisResultRepository.save(analysisResult);

            // 5. ViolationDetails
            if (analysisResult.getId() != null) {
                violationDetailRepository.deleteByAnalysisResultId(analysisResult.getId());
            }
            JsonNode violationsNode = root.path("analysis").path("violations");
            if (violationsNode.isArray()) {
                for (JsonNode vNode : violationsNode) {
                    Integer startTime = vNode.path("startTime").isMissingNode() ? null : vNode.path("startTime").asInt();
                    String violationSentence = vNode.path("violationSentence").asText("");
                    String reason = vNode.path("reason").asText("");

                    violationDetailRepository.save(ViolationDetail.builder()
                            .analysisResult(analysisResult)
                            .startTime(startTime)
                            .violationSentence(violationSentence)
                            .reason(reason)
                            .build());
                }
            }

            log.info("Successfully mapped and saved AnalysisResult for videoId={}", videoIdStr);

        } catch (Exception e) {
            // Avoid logging full payload: it may be large and can contain transcript content.
            log.error("analysis.mapping_failed payloadChars={}", resultJson == null ? 0 : resultJson.length(), e);
        }
    }

    private void mapAndSaveFromFinalPayload(JsonNode root) {
        // Expected payload fields (recommended): videoId, videoTitle, channelId, channelName, trustGrade, confidenceScore, summary, violations[]
        String videoIdStr = root.path("videoId").asText(null);
        if (videoIdStr == null || videoIdStr.isBlank()) {
            log.warn("Missing videoId in final payload resultJson");
            return;
        }

        String channelIdStr = root.path("channelId").asText(null);
        if (channelIdStr == null || channelIdStr.isBlank()) {
            // Channel.ytChannelId is non-null in RDB schema; without it we cannot persist consistently.
            log.warn("Missing channelId in final payload for videoId={}. Skipping RDB mapping.", videoIdStr);
            return;
        }

        String channelName = root.path("channelName").asText("");
        Channel channel = channelRepository.findByYtChannelId(channelIdStr)
            .orElseGet(() -> channelRepository.save(Channel.builder()
                .ytChannelId(channelIdStr)
                .channelName(channelName)
                .trustGrade(TrustGrade.UNKNOWN)
                .totalViolationCount(0)
                .build()));

        String videoTitle = root.path("videoTitle").asText("");
        Video video = videoRepository.findByYtVideoId(videoIdStr)
            .orElseGet(() -> videoRepository.save(Video.builder()
                .ytVideoId(videoIdStr)
                .title(videoTitle)
                .channel(channel)
                .build()));

        String trustGradeStr = root.path("trustGrade").asText("UNKNOWN");
        TrustGrade trustGrade;
        try {
            trustGrade = TrustGrade.valueOf(trustGradeStr.toUpperCase());
        } catch (IllegalArgumentException e) {
            trustGrade = TrustGrade.UNKNOWN;
        }

        Integer confidenceScore = root.path("confidenceScore").isMissingNode() ? null : root.path("confidenceScore").asInt();
        String summary = root.path("summary").asText("");

        // Kafka mock/worker payload currently doesn't carry modelVersion; keep a sensible default.
        String modelVersion = root.path("modelVersion").asText("unknown");

        AnalysisResult analysisResult = analysisResultRepository.save(AnalysisResult.builder()
            .video(video)
            .status(trustGrade)
            .confidenceScore(confidenceScore == null ? 0 : confidenceScore)
            .summary(summary)
            .modelVersion(modelVersion)
            .build());

        JsonNode violationsNode = root.path("violations");
        if (violationsNode.isArray()) {
            for (JsonNode vNode : violationsNode) {
                Integer startTime = vNode.path("startTime").isMissingNode() ? null : vNode.path("startTime").asInt();
                String violationSentence = vNode.path("violationSentence").asText("");
                String reason = vNode.path("reason").asText("");

                violationDetailRepository.save(ViolationDetail.builder()
                    .analysisResult(analysisResult)
                    .startTime(startTime)
                    .violationSentence(violationSentence)
                    .reason(reason)
                    .build());
            }
        }

        log.info("Successfully mapped and saved AnalysisResult(final payload) for videoId={}", videoIdStr);
    }
}
