package com.ssafy.a405.domain.analysis.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ssafy.a405.domain.analysis.entity.AnalysisResult;
import com.ssafy.a405.domain.analysis.entity.ViolationDetail;
import com.ssafy.a405.domain.analysis.repository.AnalysisResultRepository;
import com.ssafy.a405.domain.analysis.repository.ViolationDetailRepository;
import com.ssafy.a405.domain.channel.entity.Channel;
import com.ssafy.a405.domain.channel.repository.ChannelRepository;
import com.ssafy.a405.domain.video.entity.Video;
import com.ssafy.a405.domain.video.entity.VideoScript;
import com.ssafy.a405.domain.video.repository.VideoRepository;
import com.ssafy.a405.domain.video.repository.VideoScriptRepository;
import com.ssafy.a405.global.common.enums.TrustGrade;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@RequiredArgsConstructor
public class AnalysisDataMappingService {

    private final ObjectMapper objectMapper;
    private final ChannelRepository channelRepository;
    private final VideoRepository videoRepository;
    private final VideoScriptRepository videoScriptRepository;
    private final AnalysisResultRepository analysisResultRepository;
    private final ViolationDetailRepository violationDetailRepository;

    @Transactional
    public void mapAndSaveAnalysisResult(String resultJson) {
        if (resultJson == null || resultJson.isBlank()) {
            return;
        }

        try {
            JsonNode root = objectMapper.readTree(resultJson);
            JsonNode transcriptNode = root.path("transcript");
            JsonNode analysisNode = root.path("analysis").path("analysisResult");

            if (transcriptNode.isMissingNode() || analysisNode.isMissingNode()) {
                log.warn("Missing transcript or analysis node in resultJson");
                return;
            }

            // 1. Channel
            String channelIdStr = transcriptNode.path("channel_id").asText();
            String channelName = transcriptNode.path("author").asText();

            Channel channel = channelRepository.findByYtChannelId(channelIdStr)
                    .orElseGet(() -> channelRepository.save(Channel.builder()
                            .ytChannelId(channelIdStr)
                            .channelName(channelName)
                            .trustGrade(TrustGrade.UNKNOWN) // Will be updated later if needed
                            .totalViolationCount(0)
                            .build()));

            // 2. Video
            String videoIdStr = transcriptNode.path("video_id").asText();
            String videoTitle = transcriptNode.path("title").asText();

            Video video = videoRepository.findByYtVideoId(videoIdStr)
                    .orElseGet(() -> videoRepository.save(Video.builder()
                            .ytVideoId(videoIdStr)
                            .title(videoTitle)
                            .channel(channel)
                            // thumbnailUrl, description, publishedAt can be updated later if Youtube API is used directly
                            .build()));

            // 3. VideoScript
            String content = transcriptNode.path("content").asText();
            boolean isWhisper = transcriptNode.path("is_whisper").asBoolean(false);

            // Create new script if not exists (simplification)
            videoScriptRepository.save(VideoScript.builder()
                    .video(video)
                    .rawText(content)
                    .isAutoGenerated(isWhisper)
                    .build());

            // 4. AnalysisResult
            String trustGradeStr = analysisNode.path("trustGrade").asText("UNKNOWN");
            TrustGrade trustGrade;
            try {
                trustGrade = TrustGrade.valueOf(trustGradeStr.toUpperCase());
            } catch (IllegalArgumentException e) {
                trustGrade = TrustGrade.UNKNOWN;
            }

            Integer confidenceScore = analysisNode.path("confidenceScore").isMissingNode() ? null : analysisNode.path("confidenceScore").asInt();
            String summary = analysisNode.path("summary").asText("");
            String modelVersion = analysisNode.path("modelVersion").asText("unknown");

            AnalysisResult analysisResult = analysisResultRepository.save(AnalysisResult.builder()
                    .video(video)
                    .status(trustGrade)
                    .confidenceScore(confidenceScore)
                    .summary(summary)
                    .modelVersion(modelVersion)
                    .build());

            // 5. ViolationDetails
            JsonNode violationsNode = root.path("analysis").path("violations");
            if (violationsNode.isArray()) {
                for (JsonNode vNode : violationsNode) {
                    Integer startTime = vNode.path("startTime").isMissingNode() ? null : vNode.path("startTime").asInt();
                    String violationSentence = vNode.path("violationSentence").asText("");
                    String reason = vNode.path("reason").asText("");

                    violationDetailRepository.save(ViolationDetail.builder()
                            .analysisResult(analysisResult)
                            .startTime(startTime)
                            .violationSentence(violationSentence)
                            .reason(reason)
                            .build());
                }
            }

            log.info("Successfully mapped and saved AnalysisResult for videoId={}", videoIdStr);

        } catch (Exception e) {
            log.error("Failed to map and save AnalysisResult. resultJson={}", resultJson, e);
        }
    }
}
