pipeline {
    agent any

    environment {
        IMAGE_NAME = "a405-backend:latest"
        CONTAINER_NAME = "a405-backend"
        APP_PORT = "8080"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build') {
            steps {
                dir('be') {
                    sh 'docker build -t ${IMAGE_NAME} .'
                }
            }
        }

        stage('Deploy') {
            when {
                branch 'develop'
            }
            steps {
                sh '''
                    docker rm -f ${CONTAINER_NAME} || true
                    docker run -d \
                      --name ${CONTAINER_NAME} \
                      -p ${APP_PORT}:8080 \
                      ${IMAGE_NAME}
                '''
            }
        }
    }

    post {
        success {
            echo 'BE pipeline success'
        }
        failure {
            echo 'BE pipeline failed'
        }
    }
}